dist: xenial
language: python
python:
  - '3.7.3'
cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.pyenv"
before_install:
  - sudo apt-get update
install:
  - pip install -r requirements.txt
before_script:
  - sleep 1
script:
  pytest --cov=deeploy --cov-report term-missing --ignore=./deeploy/lib  --cov-config=.coveragerc __tests/
after_success:
  - codecov
  - coveralls
