pull_request = {
    "pullrequest":{
        "rendered":{
            "description":{
                "raw":"some description",
                "markup":"markdown",
                "html":"<p>some description</p>",
                "type":"rendered"
            },
            "title":{
                "raw":"add dummy text 2",
                "markup":"markdown",
                "html":"<p>add dummy text 2</p>",
                "type":"rendered"
            }
        },
        "type":"pullrequest",
        "description":"some description",
        "links":{
            "decline":{
                "href":"https://api.bitbucket.org/2.0/repositories/ukorjidechi/test-webhook/pullrequests/1/decline"
            },
            "diffstat":{
                "href":"https://api.bitbucket.org/2.0/repositories/ukorjidechi/test-webhook/diffstat/ukorjidechi/test-webhook:e8a4ec267c0f%0D9d3ff5e4acdc?from_pullrequest_id=1"
            },
            "commits":{
                "href":"https://api.bitbucket.org/2.0/repositories/ukorjidechi/test-webhook/pullrequests/1/commits"
            },
            "self":{
                "href":"https://api.bitbucket.org/2.0/repositories/ukorjidechi/test-webhook/pullrequests/1"
            },
            "comments":{
                "href":"https://api.bitbucket.org/2.0/repositories/ukorjidechi/test-webhook/pullrequests/1/comments"
            },
            "merge":{
                "href":"https://api.bitbucket.org/2.0/repositories/ukorjidechi/test-webhook/pullrequests/1/merge"
            },
            "html":{
                "href":"https://bitbucket.org/ukorjidechi/test-webhook/pull-requests/1"
            },
            "activity":{
                "href":"https://api.bitbucket.org/2.0/repositories/ukorjidechi/test-webhook/pullrequests/1/activity"
            },
            "diff":{
                "href":"https://api.bitbucket.org/2.0/repositories/ukorjidechi/test-webhook/diff/ukorjidechi/test-webhook:e8a4ec267c0f%0D9d3ff5e4acdc?from_pullrequest_id=1"
            },
            "approve":{
                "href":"https://api.bitbucket.org/2.0/repositories/ukorjidechi/test-webhook/pullrequests/1/approve"
            },
            "statuses":{
                "href":"https://api.bitbucket.org/2.0/repositories/ukorjidechi/test-webhook/pullrequests/1/statuses"
            }
        },
        "title":"add dummy text 2",
        "close_source_branch":True,
        "reviewers":[

        ],
        "id":1,
        "destination":{
            "commit":{
                "hash":"9d3ff5e4acdc",
                "type":"commit",
                "links":{
                    "self":{
                        "href":"https://api.bitbucket.org/2.0/repositories/ukorjidechi/test-webhook/commit/9d3ff5e4acdc"
                    },
                    "html":{
                        "href":"https://bitbucket.org/ukorjidechi/test-webhook/commits/9d3ff5e4acdc"
                    }
                }
            },
            "repository":{
                "links":{
                    "self":{
                        "href":"https://api.bitbucket.org/2.0/repositories/ukorjidechi/test-webhook"
                    },
                    "html":{
                        "href":"https://bitbucket.org/ukorjidechi/test-webhook"
                    },
                    "avatar":{
                        "href":"https://bytebucket.org/ravatar/%7Bc393ee4f-bf97-49bc-9bf9-5edb965773e0%7D?ts=default"
                    }
                },
                "type":"repository",
                "name":"test-webhook",
                "full_name":"ukorjidechi/test-webhook",
                "uuid":"{c393ee4f-bf97-49bc-9bf9-5edb965773e0}"
            },
            "branch":{
                "name":"master"
            }
        },
        "created_on":"2019-08-15T14:53:11.056143+00:00",
        "summary":{
            "raw":"some description",
            "markup":"markdown",
            "html":"<p>some description</p>",
            "type":"rendered"
        },
        "source":{
            "commit":{
                "hash":"c2a5cd448579",
                "type":"commit",
                "links":{
                    "self":{
                        "href":"https://api.bitbucket.org/2.0/repositories/ukorjidechi/test-webhook/commit/c2a5cd448579"
                    },
                    "html":{
                        "href":"https://bitbucket.org/ukorjidechi/test-webhook/commits/c2a5cd448579"
                    }
                }
            },
            "repository":{
                "links":{
                    "self":{
                        "href":"https://api.bitbucket.org/2.0/repositories/ukorjidechi/test-webhook"
                    },
                    "html":{
                        "href":"https://bitbucket.org/ukorjidechi/test-webhook"
                    },
                    "avatar":{
                        "href":"https://bytebucket.org/ravatar/%7Bc393ee4f-bf97-49bc-9bf9-5edb965773e0%7D?ts=default"
                    }
                },
                "type":"repository",
                "name":"test-webhook",
                "full_name":"ukorjidechi/test-webhook",
                "uuid":"{c393ee4f-bf97-49bc-9bf9-5edb965773e0}"
            },
            "branch":{
                "name":"example-1"
            }
        },
        "comment_count":0,
        "state":"MERGED",
        "task_count":0,
        "participants":[
            {
                "role":"PARTICIPANT",
                "participated_on":"2019-08-15T14:56:00.651199+00:00",
                "type":"participant",
                "approved":True,
                "user":{
                    "display_name":"Ukor Jidechi",
                    "uuid":"{d59f2ffc-8fab-47ec-9a40-88326c40425e}",
                    "links":{
                        "self":{
                            "href":"https://api.bitbucket.org/2.0/users/%7Bd59f2ffc-8fab-47ec-9a40-88326c40425e%7D"
                        },
                        "html":{
                            "href":"https://bitbucket.org/%7Bd59f2ffc-8fab-47ec-9a40-88326c40425e%7D/"
                        },
                        "avatar":{
                            "href":"https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:703818e0-735b-46f0-91c2-7802464267a9/7e09e11a-224b-4f27-ad92-2c75caecb1ed/128"
                        }
                    },
                    "nickname":"ukorjidechi",
                    "type":"user",
                    "account_id":"557058:703818e0-735b-46f0-91c2-7802464267a9"
                }
            }
        ],
        "reason":"",
        "updated_on":"2019-08-15T14:56:20.907750+00:00",
        "author":{
            "display_name":"Ukor Jidechi",
            "uuid":"{d59f2ffc-8fab-47ec-9a40-88326c40425e}",
            "links":{
                "self":{
                    "href":"https://api.bitbucket.org/2.0/users/%7Bd59f2ffc-8fab-47ec-9a40-88326c40425e%7D"
                },
                "html":{
                    "href":"https://bitbucket.org/%7Bd59f2ffc-8fab-47ec-9a40-88326c40425e%7D/"
                },
                "avatar":{
                    "href":"https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:703818e0-735b-46f0-91c2-7802464267a9/7e09e11a-224b-4f27-ad92-2c75caecb1ed/128"
                }
            },
            "nickname":"ukorjidechi",
            "type":"user",
            "account_id":"557058:703818e0-735b-46f0-91c2-7802464267a9"
        },
        "merge_commit":{
            "hash":"e8a4ec267c0f",
            "type":"commit",
            "links":{
                "self":{
                    "href":"https://api.bitbucket.org/2.0/repositories/ukorjidechi/test-webhook/commit/e8a4ec267c0f"
                },
                "html":{
                    "href":"https://bitbucket.org/ukorjidechi/test-webhook/commits/e8a4ec267c0f"
                }
            }
        },
        "closed_by":{
            "display_name":"Ukor Jidechi",
            "uuid":"{d59f2ffc-8fab-47ec-9a40-88326c40425e}",
            "links":{
                "self":{
                    "href":"https://api.bitbucket.org/2.0/users/%7Bd59f2ffc-8fab-47ec-9a40-88326c40425e%7D"
                },
                "html":{
                    "href":"https://bitbucket.org/%7Bd59f2ffc-8fab-47ec-9a40-88326c40425e%7D/"
                },
                "avatar":{
                    "href":"https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:703818e0-735b-46f0-91c2-7802464267a9/7e09e11a-224b-4f27-ad92-2c75caecb1ed/128"
                }
            },
            "nickname":"ukorjidechi",
            "type":"user",
            "account_id":"557058:703818e0-735b-46f0-91c2-7802464267a9"
        }
    },
    "repository":{
        "scm":"git",
        "website":"",
        "name":"test-webhook",
        "links":{
            "self":{
                "href":"https://api.bitbucket.org/2.0/repositories/ukorjidechi/test-webhook"
            },
            "html":{
                "href":"https://bitbucket.org/ukorjidechi/test-webhook"
            },
            "avatar":{
                "href":"https://bytebucket.org/ravatar/%7Bc393ee4f-bf97-49bc-9bf9-5edb965773e0%7D?ts=default"
            }
        },
        "full_name":"ukorjidechi/test-webhook",
        "owner":{
            "display_name":"Ukor Jidechi",
            "uuid":"{d59f2ffc-8fab-47ec-9a40-88326c40425e}",
            "links":{
                "self":{
                    "href":"https://api.bitbucket.org/2.0/users/%7Bd59f2ffc-8fab-47ec-9a40-88326c40425e%7D"
                },
                "html":{
                    "href":"https://bitbucket.org/%7Bd59f2ffc-8fab-47ec-9a40-88326c40425e%7D/"
                },
                "avatar":{
                    "href":"https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:703818e0-735b-46f0-91c2-7802464267a9/7e09e11a-224b-4f27-ad92-2c75caecb1ed/128"
                }
            },
            "nickname":"ukorjidechi",
            "type":"user",
            "account_id":"557058:703818e0-735b-46f0-91c2-7802464267a9"
        },
        "type":"repository",
        "is_private":True,
        "uuid":"{c393ee4f-bf97-49bc-9bf9-5edb965773e0}"
    },
    "actor":{
        "display_name":"Ukor Jidechi",
        "uuid":"{d59f2ffc-8fab-47ec-9a40-88326c40425e}",
        "links":{
            "self":{
                "href":"https://api.bitbucket.org/2.0/users/%7Bd59f2ffc-8fab-47ec-9a40-88326c40425e%7D"
            },
            "html":{
                "href":"https://bitbucket.org/%7Bd59f2ffc-8fab-47ec-9a40-88326c40425e%7D/"
            },
            "avatar":{
                "href":"https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:703818e0-735b-46f0-91c2-7802464267a9/7e09e11a-224b-4f27-ad92-2c75caecb1ed/128"
            }
        },
        "nickname":"ukorjidechi",
        "type":"user",
        "account_id":"557058:703818e0-735b-46f0-91c2-7802464267a9"
    }
}

headers = {
    'X-EVENT-KEY': 'pullrequest:fulfilled',
    'X-HOOK-UUID': '4ba531fd-299e-424d-acc6-372e0deb36ee',
    'X-REQUEST-UUID': '08c62d10-1222-4151-934e-c74ea5f5edc6',
    # 'X-ATTEMPT-NUMBER': 1
}
