# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "dev_requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv deeploy
            . deeploy/bin/activate
            pip install -r dev_requirements.txt

      - save_cache:
          paths:
            - ./deeploy
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: |
            . deeploy/bin/activate
            pytest --cov=deeploy --cov-report term-missing --ignore=./deeploy/lib  --cov-config=.coveragerc __tests/
            codecov
            coveralls --config_file=.coveragerc

      - store_artifacts:
          path: test-reports
          destination: test-reports
